### ISSUE TITLE
ERD Issues

### ISSUE THREAD

**Issue by CaddyJunior** [Makizoro/Overclock#10]
We need the CSI_id to be explained.
in the Club table we were thinking of adding Club_name in the club table

**Comment by TarshenNaidoo** [comment]
CSI_id is just the primary key identifier used to find unique CSI records. We could instead make CSI_name the primary instead of CSI_id and use that as both a foreign key and primary key in the Club, Society and Interest Group tables as well. That would also address the 2nd point

**Comment by TarshenNaidoo** [comment]
We'll use CSI_name as primary key
